# Generated by Django 6.1 on 2026-09-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('result', '0005_phones_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='phones',
            name='login_require',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='phones',
            name='image',
            field=models.ImageField(default='store/default.jpg', upload_to='store/'),
        ),
    ]
